project_id = "rydafpzgudalfkyorofh"

[functions.fetch-instagram]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.admin-login-notify]
verify_jwt = false

[functions.ai-search-suggest]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false

[functions.get-captcha-config]
verify_jwt = false
